[package]
name = "custodian-set-manager"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
custom-panic = []
custom-heap = []

[dependencies]
solana-program = { workspace = true }
bytemuck = { workspace = true }
